using CouchCoop.MirrorProtocol.SceneModel;

namespace CouchCoop.MirrorProtocol.Tests;

// C# reader leg for the EXTENDED wire-fixture corpus (spine / particle / intent-frames / tween-hints / order-patch),
// each generated byte-exactly by the server serializer (BrowserSceneDeltaMessageTests) and asserted in parallel by
// the TS suites. Every fixture is fed through the shared SceneDeltaReader/SceneTreeApplier and checked field-by-
// field, so the three legs stay in lockstep. (Filled once the fixtures exist; skips silently if a file is absent so
// the runner stays green during bootstrap.)
internal static class NewFixtureReaderTests
{
    public static void Run()
    {
        SpineNode();
        SpineVfxBiteNode();
        ParticleNode();
        IntentFramesNode();
        Line2DNode();
        ShaderParamsNode();
        TweenHints();
        CardFlights();
        CardFlightKinds();
        OrderPatchDelta();
    }

    private static MirrorState? ApplyFixture(string file)
    {
        var path = TestFixtures.WirePath(file);
        if (!File.Exists(path))
        {
            return null;
        }

        var delta = SceneDeltaReader.Parse(File.ReadAllText(path));
        Check.That(delta is not null, $"{file}: parsed");
        var state = MirrorState.Create();
        SceneTreeApplier.ApplySceneDelta(state, delta!);
        return state;
    }

    private static void SpineNode()
    {
        if (ApplyFixture("spine-node.json") is not { } state)
        {
            return;
        }

        var spine = state.Nodes["spine"];
        Check.Equal(spine.NodeType, "SpineSprite", "spine.nodeType");
        Check.Equal(spine.SpineSceneResPath, "res://scenes/enemy.tscn", "spine.sceneResPath");
        Check.Equal(spine.SpineNodePath, "Skeleton", "spine.nodePath");
        Check.That(spine.SpineAnimations is { Count: 2 }, "spine.animations count");
        Check.Equal(spine.SpineAnimations![0], "idle", "spine.animations[0]");
        Check.Equal(spine.SpineAnimations[1], "attack", "spine.animations[1]");
        Check.Equal(spine.SpineCurrentAnim, "attack", "spine.currentAnim (volatile)");
        Check.Equal(spine.SpineTrackTime, 0.5, "spine.trackTime (volatile)");
        Check.Equal(spine.SpineLooping, false, "spine.looping false (one-shot)");
    }

    // The bite attack overlay: a ONE-SHOT spine node. `spineLooping:false` rides in the same message that starts
    // the clip, which is the whole one-shot contract on the wire — the client clamps on the last frame, so no
    // "animation finished" message is ever needed (round-8 item 10).
    private static void SpineVfxBiteNode()
    {
        if (ApplyFixture("spine-vfx-bite-node.json") is not { } state)
        {
            return;
        }

        var bite = state.Nodes["vfx-bite"];
        Check.Equal(bite.NodeType, "SpineSprite", "bite.nodeType");
        Check.Equal(bite.SpineSceneResPath, "res://scenes/vfx/vfx_bite.tscn", "bite.sceneResPath");
        Check.Equal(bite.SpineNodePath, "SpineSprite", "bite.nodePath");
        Check.That(bite.SpineAnimations is { Count: 1 }, "bite.animations count");
        Check.Equal(bite.SpineAnimations![0], "bite", "bite.animations[0]");
        Check.Equal(bite.SpineCurrentAnim, "bite", "bite.currentAnim");
        Check.Equal(bite.SpineLooping, false, "bite.looping false (plays ONCE, no end message needed)");
    }

    private static void ParticleNode()
    {
        if (ApplyFixture("particle-node.json") is not { } state)
        {
            return;
        }

        var p = state.Nodes["glow"];
        Check.That(p.ParticleSpec is not null, "particleSpec not null");
        Check.Equal(p.ParticleSpec!.Kind, "GPUParticles2D", "particle.kind");
        Check.Equal(p.ParticleSpec.Amount, 24.0, "particle.amount");
        Check.Equal(p.ParticleSpec.Lifetime, 1.5, "particle.lifetime");
        Check.Equal(p.ParticleSpec.OneShot, true, "particle.oneShot");
        Check.Equal(p.ParticleSpec.Emitting, false, "particle spec.emitting placeholder false");
        // baseColor arrived as {html} → channels derived.
        Check.SequenceClose(p.ParticleSpec.BaseColor, [1, 0.5019607843137255, 0.25098039215686274, 1], "particle.baseColor");
        Check.Equal(p.ParticleEmitting, true, "particleEmitting volatile true");
        Check.Equal(p.ParticleRestartEpoch, 2L, "particleRestartEpoch volatile");
    }

    private static void IntentFramesNode()
    {
        if (ApplyFixture("intent-frames-node.json") is not { } state)
        {
            return;
        }

        var intent = state.Nodes["intent"];
        Check.That(intent.IntentFrames is not null, "intentFrames not null");
        Check.Equal(intent.IntentFrames!.AnimationName, "attack", "intent.animationName");
        Check.Equal(intent.IntentFrames.Fps, 15.0, "intent.fps");
        Check.That(intent.IntentFrames.Frames.Count == 2, "intent frame count");
        // applyIntentFrame0: node texture forced to frame 0.
        Check.Equal(intent.TextureUrl, intent.IntentFrames.Frames[0].Url, "intent frame-0 texture override");
        Check.Equal(intent.IntentFrames.Frames[0].Url, "/res/images/intent_atlas.png", "intent frame0 url");
        Check.That(intent.TextureRegion is not null, "intent frame-0 region applied");
    }

    // A map quill stroke: the whole appearance is linePoints + lineWidth + lineColor. The reader must produce the
    // flat NODE-LOCAL array verbatim (no re-pairing, no transform applied) and must leave LocalRect NULL — the
    // producer streams none for a Line2D, which is precisely why `LinePoints != null` is the "this node paints"
    // signal in both renderers. Pen-vs-eraser rides the shader path, so assert it survives too.
    private static void Line2DNode()
    {
        if (ApplyFixture("line2d-node.json") is not { } state)
        {
            return;
        }

        var stroke = state.Nodes["stroke"];
        Check.Equal(stroke.NodeType, "Godot.Line2D", "stroke.nodeType");
        Check.That(stroke.LinePoints is { Count: 6 }, "stroke.linePoints flat length (3 points)");
        Check.SequenceClose(stroke.LinePoints, [17, 98, 457, 249, 390.25, 554.5], "stroke.linePoints verbatim");
        Check.Equal(stroke.LineWidth, 4.0, "stroke.lineWidth");
        Check.That(stroke.LineColor is not null, "stroke.lineColor not null");
        Check.Equal(stroke.LineColor!.Html, "#ff0000ff", "stroke.lineColor html");
        Check.Equal(stroke.LocalRect, null, "a Line2D streams NO localRect (linePoints is the paint signal)");
        Check.Equal(stroke.ShaderId, "res://shaders/map_drawing/line_draw.gdshader",
            "stroke shader path (pen vs eraser discriminator — no eraser flag on the wire)");
    }

    private static void ShaderParamsNode()
    {
        if (ApplyFixture("shader-params-node.json") is not { } state)
        {
            return;
        }

        var node = state.Nodes["shaded"];
        Check.That(node.ShaderParams is { Count: 7 }, "shaderParams count");
        var byName = node.ShaderParams!.ToDictionary(p => p.Name);

        Check.Equal(byName["width"].Kind, "number", "width.kind");
        Check.Equal(byName["width"].Number, 0.075, "width.number");

        var center = byName["center"];
        Check.Equal(center.Kind, "vector2", "center.kind");
        Check.That(center.Vector2 is { } v2 && v2.X == 0.5 && v2.Y == 0.25, "center.vector2");

        var tint3 = byName["tint3"];
        Check.Equal(tint3.Kind, "vector3", "tint3.kind");
        Check.That(tint3.Vector3 is { } v3 && v3.X == 1 && v3.Y == 0.5 && v3.Z == 0.25, "tint3.vector3 {x,y,z}");

        var tint4 = byName["tint4"];
        Check.Equal(tint4.Kind, "vector4", "tint4.kind");
        Check.That(tint4.Vector4 is { } v4 && v4.X == 0.25 && v4.Y == 0.5 && v4.Z == 0.75 && v4.W == 1, "tint4.vector4 {x,y,z,w}");

        var bounds = byName["bounds"];
        Check.Equal(bounds.Kind, "rect2", "bounds.kind");
        Check.That(bounds.Rect2 is { } r && r.X == 0 && r.Y == 0 && r.Width == 128 && r.Height == 64, "bounds.rect2 {x,y,width,height}");

        var xform = byName["xform"];
        Check.Equal(xform.Kind, "transform2d", "xform.kind");
        Check.SequenceClose(xform.Transform2D, [1, 0, 0, 1, 640, 360], "xform.transform2d 6-tuple");

        var palette = byName["palette"];
        Check.Equal(palette.Kind, "vector3Array", "palette.kind");
        Check.SequenceClose(palette.NumberArray, [1, 0, 0, 0, 1, 0], "palette.numberArray flattened");
    }

    private static void TweenHints()
    {
        if (ApplyFixture("tween-hints-delta.json") is not { } state)
        {
            return;
        }

        Check.That(state.PendingHints.Count == 3, "3 tween hints accumulated");

        var move = state.PendingHints[0];
        Check.Equal(move.TargetId, "card", "hint0.targetId");
        Check.Equal(move.Property, "position", "hint0.property");
        Check.Equal(move.Group, "g1", "hint0.group");
        Check.SequenceClose(move.EndTransform, [1, 0, 0, 1, 640, 360], "hint0.endTransform");

        var fade = state.PendingHints[1];
        Check.Equal(fade.Property, "modulate:a", "hint1.property");
        Check.Equal(fade.Group, "g1", "hint1.group");
        Check.Equal(fade.EndOpacity, 0.0, "hint1.endOpacity");

        var loop = state.PendingHints[2];
        Check.Equal(loop.Property, "scale", "hint2.property (timing-only loop)");
        Check.Equal(loop.EndTransform, null, "hint2 no endpoint (looping)");
        Check.Equal(loop.DurationMs, 800.0, "hint2.durationMs");
    }

    // WS-3: the declarative card flights, read from the bytes the server serializer actually produces. The TS leg
    // (wireFixtureCorpus.spec.ts) asserts the SAME fixture field-for-field, so a rename or an arity change on either
    // reader breaks here — which matters more than for a tween hint, because the producer stops streaming the
    // flight's node and a dropped flight leaves it frozen.
    private static void CardFlights()
    {
        if (ApplyFixture("card-flight-delta.json") is not { } state)
        {
            return;
        }

        Check.That(state.PendingCardFlights.Count == 2, "2 card flights accumulated");
        Check.That(state.PendingHints.Count == 0, "flights never leak into the tween-hint array");

        var withTrail = state.PendingCardFlights[0];
        Check.Equal(withTrail.TargetId, "41", "flight0.targetId");
        Check.Equal(withTrail.TrailId, "42", "flight0.trailId");
        Check.SequenceClose(withTrail.Start, [300, 880], "flight0.start");
        Check.SequenceClose(withTrail.End, [1620, 880], "flight0.end");
        Check.SequenceClose(withTrail.Control, [960, 280], "flight0.control");
        Check.SequenceClose(withTrail.Basis, [1, 0, 0, 1], "flight0.basis");
        Check.Close(withTrail.Speed0, 1.18, "flight0.speed0");
        Check.Close(withTrail.Accel, 2.3, "flight0.accel");
        Check.Close(withTrail.Duration, 1.4, "flight0.duration");
        Check.Close(withTrail.Scale0, 1, "flight0.scale0");
        Check.Close(withTrail.WindowMs, 3600, "flight0.windowMs");

        // The no-trail flight: the producer OMITS `trailId` entirely (WhenWritingNull), so this also pins that an
        // absent key reads as null rather than as an id that would join to nothing.
        var noTrail = state.PendingCardFlights[1];
        Check.Equal(noTrail.TargetId, "51", "flight1.targetId");
        Check.That(noTrail.TrailId is null, "flight1.trailId absent ⇒ null");
        Check.SequenceClose(noTrail.Basis, [0.5, 0, 0, 0.5], "flight1.basis (a scaled parent chain)");
        Check.Close(noTrail.Scale0, 0.5, "flight1.scale0");

        // Every entry in the pre-R13 fixture is a shuffle, and it says so WITHOUT the key existing — the reader
        // normalizes the absence, so nothing downstream branches on null.
        Check.Equal(withTrail.Kind, "shuffle", "flight0.kind (absent ⇒ shuffle)");
        Check.Close(withTrail.Rot0, 0, "flight0.rot0 (absent ⇒ 0)");
        Check.Equal(noTrail.Kind, "shuffle", "flight1.kind (absent ⇒ shuffle)");
    }

    // R13: one array, both kinds. The TS leg (wireFixtureCorpus.spec.ts) asserts the same three entries. The third
    // is the one that matters most: a kind this build has never seen must come out as the shuffle motion, because a
    // dropped flight leaves a card frozen (the producer stopped streaming it) while wrong-flavoured motion does not.
    private static void CardFlightKinds()
    {
        if (ApplyFixture("card-flight-discard-delta.json") is not { } state)
        {
            return;
        }

        Check.That(state.PendingCardFlights.Count == 3, "3 card flights accumulated");

        var discard = state.PendingCardFlights[0];
        Check.Equal(discard.TargetId, "61", "discard.targetId");
        Check.Equal(discard.Kind, "discard", "discard.kind round-trips");
        Check.Close(discard.Rot0, -0.35, "discard.rot0 (the resting angle it turns out of)");
        Check.SequenceClose(discard.Start, [960, 1180], "discard.start (the hand, not a pile)");
        Check.Close(discard.WindowMs, 3200, "discard.windowMs");

        var legacy = state.PendingCardFlights[1];
        Check.Equal(legacy.TargetId, "71", "legacy.targetId");
        Check.Equal(legacy.Kind, "shuffle", "legacy entry (neither key) ⇒ shuffle");
        Check.Close(legacy.Rot0, 0, "legacy entry ⇒ rot0 0");

        var unknown = state.PendingCardFlights[2];
        Check.Equal(unknown.TargetId, "81", "unknown.targetId");
        Check.Equal(unknown.Kind, "shuffle", "an unrecognised kind fails OPEN to shuffle, never to a drop");
        Check.Close(unknown.Rot0, 0.75, "an unrecognised kind still carries its rot0 through");
    }

    private static void OrderPatchDelta()
    {
        if (ApplyFixture("order-patch-full.json") is not { } fullState)
        {
            return;
        }

        // The keyframe fixture establishes the base order; the patch fixture rides on top.
        Check.SequenceEqual(fullState.OrderedIds, ["R", "a", "b", "c"], "order-patch base order");

        var patch = SceneDeltaReader.Parse(TestFixtures.ReadWire("order-patch-delta.json"));
        Check.That(patch is not null, "order patch delta parsed");
        Check.That(patch!.OrderPatch is not null, "order patch present (not full array)");
        SceneTreeApplier.ApplySceneDelta(fullState, patch);
        Check.SequenceEqual(fullState.OrderedIds, ["R", "c", "a", "b"], "order after patch");
    }
}
