using System.Text;
using CouchCoop.Mod.Protocol;
using CouchCoop.Mod.Server;
using Spirectl.Sts2.Core.SceneInspection;

// Wire-diet serialization checks for BrowserSceneDeltaMessage: the leaf converters slim colors to #RRGGBBAA-only,
// Vector2-composed numbers to float32 shortest round-trip, and resource refs to their path — everywhere in the
// graph (top-level + nested) — while the discriminator suffix and camelCase/omit-null shape stay intact. Also a
// precision guard: the float32 cast is lossless for the producer's float-origin transforms. Pure; assert-or-throw.
internal static class BrowserSceneDeltaMessageTests
{
    public static void Run()
    {
        ColorSerializesHtmlOnly();
        Vector2SerializesFloatShortestRoundTrip();
        ResourceRefSerializesPathOnly();
        NestedColorsInTextAreSlimmed();
        DiscriminatorSuffixAndShapeIntact();
        FloatCastLosslessForProducerTransforms();
        GoldenBytesForRepresentativeNode();
        DefaultValuedFieldsAreOmitted();
        MeaningfulNonDefaultsAreWritten();
        ContentKeyReachesTheWire();
        RichRoleFontsReachTheWire();
        ClipContentsReachesTheWire();
        FocusedReachesTheWire();
        RoundTripFixtureMatches();
        SpineNodeFixtureMatches();
        SpineVfxBiteNodeFixtureMatches();
        ParticleNodeFixtureMatches();
        IntentFramesNodeFixtureMatches();
        Line2DNodeFixtureMatches();
        LineGeometryReachesTheWire();
        ShaderParamsNodeFixtureMatches();
        TweenHintsDeltaFixtureMatches();
        CardFlightsDeltaFixtureMatches();
        CardFlightDiscardDeltaFixtureMatches();
        OrderPatchFixturesMatch();
    }

    // The cross-language round-trip fixture: this exact delta serializes to tests/fixtures/wire/roundtrip-delta.json,
    // which roundTripFixture.spec.ts feeds through parseSceneDelta/applySceneDelta and asserts field-by-field. Both
    // sides read the same checked-in bytes, so a wire-format change on either side breaks a test.
    internal static RuntimeSceneDelta RoundTripDelta()
    {
        var root = new RuntimeSceneNodeDelta(
            Id: "root", ParentId: null, Name: "Root", NodeType: "Node2D", Rect: null,
            Visible: true, Opacity: 1, ZIndex: null, Rotation: 0, Texture: null, NinePatch: false, Text: null)
        {
            Transform = new RuntimeSceneTransform2DSnapshot(new(1, 0), new(0, 1), new(0, 0)),
        };
        var text = new RuntimeSceneTextPropertiesSnapshot(
            Text: "HP", RawText: null, RichTextEnabled: null, Source: "label", DiagnosticSurface: "surf",
            Font: null, FontSize: null, LineHeight: null,
            TextColor: new RuntimeSceneColorSnapshot(1, 1, 1, 1, "#ffffffff"),
            OutlineColor: null, OutlineSize: null, Shadow: null, RichTextSpans: [], Notices: [],
            AppliedFontSize: 24,
            Layout: new RuntimeSceneTextLayoutSnapshot("center", "center", null, null, null, null, null, null, null, []));
        var card = new RuntimeSceneNodeDelta(
            Id: "card", ParentId: "root", Name: "Card", NodeType: "Control", Rect: null,
            Visible: false, Opacity: 0.5, ZIndex: 5, Rotation: 0,
            Texture: new RuntimeSceneResourceRefSnapshot("Texture", "res://images/card.png", "Texture2D", "card"),
            NinePatch: false, Text: text)
        {
            Modulate = new RuntimeSceneColorSnapshot(1, 0.5, 0.25, 1, "#ff8040ff"),
            ScaleX = 1, ScaleY = 2,
            Transform = new RuntimeSceneTransform2DSnapshot(new(1, 0), new(0, 1), new((double)960.5f, (double)540f)),
            LocalRect = new RuntimeSceneRect2Snapshot(new(0, 0), new((double)100f, (double)16f)),
        };
        return new RuntimeSceneDelta(true, "run", "screen:run:live", [root, card], [], ["root", "card"]);
    }

    private static void RoundTripFixtureMatches()
    {
        var json = Serialize(RoundTripDelta());
        var expected = File.ReadAllText(WireFixturePath("roundtrip-delta.json")).TrimEnd('\n', '\r');
        Assert(json == expected, $"round-trip fixture matches serialization; got:\n{json}");
    }

    // ---- extended cross-language corpus (spine / particle / intent / tween / order-patch) -----------------------
    // Each fixture below is GENERATED byte-exactly by this server serializer and consumed by BOTH the TS suite
    // (frontend/src/mirror/__tests__/wireFixtureCorpus.spec.ts) and the C# reader
    // (tests/CouchCoop.MirrorProtocol.Tests/NewFixtureReaderTests.cs) — three-way lockstep. Set
    // COUCHCOOP_WIRE_FIXTURE_REGEN=1 to (re)write the files from this serializer; otherwise they are asserted
    // byte-for-byte, exactly like RoundTripFixtureMatches.
    private static void AssertOrWriteFixture(string file, string json)
    {
        var path = WireFixturePath(file);
        var regen = Environment.GetEnvironmentVariable("COUCHCOOP_WIRE_FIXTURE_REGEN") == "1";
        if (regen || !File.Exists(path))
        {
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            File.WriteAllText(path, json + "\n");
            return;
        }

        var expected = File.ReadAllText(path).TrimEnd('\n', '\r');
        Assert(json == expected, $"{file} matches serialization; got:\n{json}");
    }

    // A SpineSprite: static spine block (scene/node/anims) + volatile current-anim/track-time/looping (one-shot).
    private static void SpineNodeFixtureMatches()
    {
        var spine = new RuntimeSceneNodeDelta(
            Id: "spine", ParentId: null, Name: "Enemy", NodeType: "SpineSprite", Rect: null,
            Visible: true, Opacity: 1, ZIndex: null, Rotation: 0, Texture: null, NinePatch: false, Text: null)
        {
            Spine = new RuntimeSceneSpineSnapshot("res://scenes/enemy.tscn", "Skeleton", ["idle", "attack"]),
            SpineCurrentAnim = "attack",
            SpineTrackTime = 0.5,
            SpineLooping = false,
        };
        AssertOrWriteFixture("spine-node.json", Serialize(FullDelta(spine)));
    }

    // The bite attack overlay (res://scenes/vfx/vfx_bite.tscn — the game's NVfxSpine driver plays its single
    // clip with loop:false and frees the node on animation_completed). The ONE-SHOT information rides entirely
    // in this START message as `spineLooping:false`: both clients clamp on the clip's last frame when it is
    // false, so the overlay plays once and needs no "animation finished" message on the wire at all. Guards the
    // round-8 item-10 regression, where the producer reported the overlay as looping and it replayed forever.
    private static void SpineVfxBiteNodeFixtureMatches()
    {
        var bite = new RuntimeSceneNodeDelta(
            Id: "vfx-bite", ParentId: null, Name: "SpineSprite", NodeType: "SpineSprite", Rect: null,
            Visible: true, Opacity: 1, ZIndex: null, Rotation: 0, Texture: null, NinePatch: false, Text: null)
        {
            Spine = new RuntimeSceneSpineSnapshot("res://scenes/vfx/vfx_bite.tscn", "SpineSprite", ["bite"]),
            SpineCurrentAnim = "bite",
            SpineTrackTime = 0.12,
            SpineLooping = false,
        };
        AssertOrWriteFixture("spine-vfx-bite-node.json", Serialize(FullDelta(bite)));
    }

    // A GPUParticles2D: static particleSpec + volatile emitting/restartEpoch. baseColor ships html-only.
    private static void ParticleNodeFixtureMatches()
    {
        var glow = new RuntimeSceneNodeDelta(
            Id: "glow", ParentId: null, Name: "Glow", NodeType: "GPUParticles2D", Rect: null,
            Visible: true, Opacity: 1, ZIndex: null, Rotation: 0, Texture: null, NinePatch: false, Text: null)
        {
            ParticleSpec = ParticleSpec(),
            ParticleEmitting = true,
            ParticleRestartEpoch = 2,
        };
        AssertOrWriteFixture("particle-node.json", Serialize(FullDelta(glow)));
    }

    // The enemy-intent glyph: an intentFrames set (2 atlas-crop frames). The client forces the node's texture to
    // frame 0.
    private static void IntentFramesNodeFixtureMatches()
    {
        var intent = new RuntimeSceneNodeDelta(
            Id: "intent", ParentId: null, Name: "Intent", NodeType: "Sprite2D", Rect: null,
            Visible: true, Opacity: 1, ZIndex: null, Rotation: 0, Texture: null, NinePatch: false, Text: null)
        {
            IntentFrames = new RuntimeSceneIntentFramesSnapshot("attack", 15,
            [
                new RuntimeSceneIntentFrameSnapshot("res://images/intent_atlas.png",
                    new RuntimeSceneRect2Snapshot(new(0, 0), new(32, 32)), new RuntimeSceneRect2Snapshot(new(0, 0), new(0, 0))),
                new RuntimeSceneIntentFrameSnapshot("res://images/intent_atlas.png",
                    new RuntimeSceneRect2Snapshot(new(32, 0), new(32, 32)), new RuntimeSceneRect2Snapshot(new(0, 0), new(0, 0))),
            ]),
        };
        AssertOrWriteFixture("intent-frames-node.json", Serialize(FullDelta(intent)));
    }

    // A map quill stroke: a `Line2D` under the map's DrawViewport. Note what is NOT here — no localRect, no texture,
    // no text: the producer measures no box for a Line2D, so `linePoints` is the ONLY thing that tells a client this
    // node paints at all. The 2x transform is the viewport-prefix fit the watcher already streams, and the shader
    // path is what discriminates pen (line_draw) from eraser (line_erase) — no eraser flag exists on the wire.
    private static void Line2DNodeFixtureMatches()
    {
        var stroke = new RuntimeSceneNodeDelta(
            Id: "stroke", ParentId: null, Name: "map_line_draw", NodeType: "Godot.Line2D", Rect: null,
            Visible: true, Opacity: 1, ZIndex: null, Rotation: 0, Texture: null, NinePatch: false, Text: null)
        {
            SceneFilePath = "res://scenes/screens/map/map_line_draw.tscn",
            Shader = new RuntimeSceneResourceRefSnapshot(
                "Shader", "res://shaders/map_drawing/line_draw.gdshader", "Shader", "line_draw"),
            Transform = new RuntimeSceneTransform2DSnapshot(new(2, 0), new(0, 2), new(1160.5, 618)),
            LinePoints = [17, 98, 457, 249, 390.25, 554.5],
            LineWidth = 4,
            LineColor = new RuntimeSceneColorSnapshot(1, 0, 0, 1, "#ff0000ff"),
        };
        AssertOrWriteFixture("line2d-node.json", Serialize(FullDelta(stroke)));
    }

    // LINE2D STROKE GEOMETRY: the ContentKey / rich-role-font lesson again — WireNodeDelta is an EXPLICIT
    // field-by-field projection, so a producer field is SILENTLY DROPPED unless FromNode lists it, and the wire is
    // the ONLY place that can be caught (the static-field lockstep reflects over the producer record, never the DTO).
    // Prove all three reach the wire under the camelCase names both readers use, that an EMPTY points array (the
    // "stroke cleared" instruction) SURVIVES rather than being defaulted away, and that a node with none of them
    // (every node off the map) still omits all three so the wire elsewhere is byte-identical.
    private static void LineGeometryReachesTheWire()
    {
        var json = Serialize(Delta(Node("stroke") with
        {
            LinePoints = [17, 98, 457, 249],
            LineWidth = 12,
            LineColor = new RuntimeSceneColorSnapshot(1, 0, 0, 1, "#ff0000ff"),
        }));
        Assert(json.Contains("\"linePoints\":[17,98,457,249]", StringComparison.Ordinal),
            $"linePoints projected onto the wire as a flat array; got: {json}");
        Assert(json.Contains("\"lineWidth\":12", StringComparison.Ordinal), "lineWidth on the wire");
        Assert(json.Contains("\"lineColor\":{\"html\":\"#ff0000ff\"}", StringComparison.Ordinal),
            "lineColor on the wire, slimmed to html by the shared colour converter");

        // EMPTY is meaningful ("the stroke was cleared — erase it"), and must never be confused with omitted
        // ("unchanged — keep the retained geometry"). Nothing in the DTO may default it away.
        var cleared = Serialize(Delta(Node("stroke") with { LinePoints = [] }));
        Assert(cleared.Contains("\"linePoints\":[]", StringComparison.Ordinal),
            $"an EMPTY linePoints array survives to the wire (the clear/undo instruction); got: {cleared}");

        var plain = Serialize(Delta(Node("a")));
        Assert(!plain.Contains("\"line", StringComparison.Ordinal),
            "all three line fields omitted for a non-Line2D node (wire unchanged off the map)");
    }

    // A ShaderMaterial node whose shaderParameters exercise BOTH the base kinds (number, vector2) and the
    // Godot-native-first extended kinds (vector3/vector4/rect2/transform2d + a flattened vector3Array). The
    // reader legs (wireFixtureCorpus.spec.ts, NewFixtureReaderTests.cs) assert each kind field-by-field.
    private static void ShaderParamsNodeFixtureMatches()
    {
        var shaded = new RuntimeSceneNodeDelta(
            Id: "shaded", ParentId: null, Name: "Shaded", NodeType: "Sprite2D", Rect: null,
            Visible: true, Opacity: 1, ZIndex: null, Rotation: 0, Texture: null, NinePatch: false, Text: null)
        {
            ShaderParameters =
            [
                new RuntimeSceneShaderParamSnapshot("width", "number", Number: 0.075),
                new RuntimeSceneShaderParamSnapshot("center", "vector2", Vector2: new RuntimeSceneVector2Snapshot(0.5, 0.25)),
                new RuntimeSceneShaderParamSnapshot("tint3", "vector3", Vector3: new RuntimeSceneVector3Snapshot(1, 0.5, 0.25)),
                new RuntimeSceneShaderParamSnapshot("tint4", "vector4", Vector4: new RuntimeSceneVector4Snapshot(0.25, 0.5, 0.75, 1)),
                new RuntimeSceneShaderParamSnapshot("bounds", "rect2", Rect2: new RuntimeSceneShaderRectSnapshot(0, 0, 128, 64)),
                new RuntimeSceneShaderParamSnapshot("xform", "transform2d", Transform2D: [1, 0, 0, 1, 640, 360]),
                new RuntimeSceneShaderParamSnapshot("palette", "vector3Array", NumberArray: [1, 0, 0, 0, 1, 0]),
            ],
        };
        AssertOrWriteFixture("shader-params-node.json", Serialize(FullDelta(shaded)));
    }

    // A delta carrying tween hints: a transform + opacity pair sharing group "g1", plus a looping (timing-only)
    // hint with no resolved endpoint.
    private static void TweenHintsDeltaFixtureMatches()
    {
        var hints = new List<TweenHintDelta>
        {
            new("card", "position", To: null, DurationMs: 300, Trans: "TRANS_CUBIC", Ease: "EASE_OUT",
                EndTransform: [1, 0, 0, 1, 640, 360], Group: "g1"),
            new("card", "modulate:a", To: null, DurationMs: 300, Trans: "TRANS_LINEAR", Ease: "EASE_IN",
                EndOpacity: 0, Group: "g1"),
            // loops>0 → the producer resolves no endpoint; a timing-only hint.
            new("spinner", "scale", To: null, DurationMs: 800, Trans: "TRANS_SINE", Ease: "EASE_IN_OUT"),
        };
        var delta = new RuntimeSceneDelta(false, "run", "screen:run:live", [], [], null, hints);
        AssertOrWriteFixture("tween-hints-delta.json", Serialize(delta));
    }

    // WS-3: a delta carrying declarative card flights — the shuffle case (one per shuffled card) with a trail, plus
    // one flight the game made no trail for. These ride their OWN array, never `hints`, and every point/basis is a
    // streamed-space GLOBAL value, so the fixture also pins that the two readers agree on the arity of each.
    private static void CardFlightsDeltaFixtureMatches()
    {
        var flights = new List<CardFlightHintDelta>
        {
            new(TargetId: "41", TrailId: "42",
                Start: [300, 880], End: [1620, 880], Control: [960, 280], Basis: [1, 0, 0, 1],
                Speed0: 1.18, Accel: 2.3, Duration: 1.4, Scale0: 1, WindowMs: 3600),
            new(TargetId: "51", TrailId: null,
                Start: [1620, 880], End: [300, 880], Control: [960, 1480], Basis: [0.5, 0, 0, 0.5],
                Speed0: 1.1, Accel: 2, Duration: 1, Scale0: 0.5, WindowMs: 2800),
        };
        var delta = new RuntimeSceneDelta(false, "run", "screen:run:live", [], [], null, CardFlights: flights);
        AssertOrWriteFixture("card-flight-delta.json", Serialize(delta));
    }

    // R13: the SAME array carrying the second flight kind. Three entries, one per case both readers must agree on:
    // an explicit "discard" (the hand→discard fly, which also carries the resting angle it turns out of), a legacy
    // entry with neither key (what every shuffle entry still serializes to), and an entry whose kind this build has
    // never heard of — which must fail OPEN to the shuffle motion rather than being dropped, since dropping it would
    // leave a suppressed card frozen.
    private static void CardFlightDiscardDeltaFixtureMatches()
    {
        var flights = new List<CardFlightHintDelta>
        {
            new(TargetId: "61", TrailId: "62",
                Start: [960, 1180], End: [1740, 980], Control: [1350, 760], Basis: [1, 0, 0, 1],
                Speed0: 1.2, Accel: 2.1, Duration: 1.2, Scale0: 1, WindowMs: 3200,
                Kind: "discard", Rot0: -0.35),
            new(TargetId: "71", TrailId: null,
                Start: [300, 880], End: [1620, 880], Control: [960, 280], Basis: [1, 0, 0, 1],
                Speed0: 1.15, Accel: 2.4, Duration: 1.5, Scale0: 1, WindowMs: 3800),
            new(TargetId: "81", TrailId: null,
                Start: [1620, 880], End: [300, 880], Control: [960, 1480], Basis: [0.5, 0, 0, 0.5],
                Speed0: 1.1, Accel: 2, Duration: 1, Scale0: 0.5, WindowMs: 2800,
                Kind: "supernova", Rot0: 0.75),
        };
        var delta = new RuntimeSceneDelta(false, "run", "screen:run:live", [], [], null, CardFlights: flights);
        var json = Serialize(delta);

        // A shuffle entry's BYTES are the contract with already-deployed clients: adding the two fields must not add
        // a key to it. Asserted on the entry itself (not the whole payload, which does carry both keys elsewhere).
        var legacyEntry = json[json.IndexOf("\"71\"", StringComparison.Ordinal)..];
        legacyEntry = legacyEntry[..legacyEntry.IndexOf('}')];
        Assert(!legacyEntry.Contains("\"kind\"", StringComparison.Ordinal), "a shuffle entry writes no kind key");
        Assert(!legacyEntry.Contains("\"rot0\"", StringComparison.Ordinal), "a shuffle entry writes no rot0 key");

        // The discard entry carries both, camelCased like every other field.
        Assert(json.Contains("\"kind\":\"discard\"", StringComparison.Ordinal), "discard entry writes its kind");
        Assert(json.Contains("\"rot0\":-0.35", StringComparison.Ordinal), "discard entry writes its rot0");

        AssertOrWriteFixture("card-flight-discard-delta.json", json);
    }

    // The order-patch pair: a keyframe establishing [R,a,b,c], then a non-full delta whose compact orderPatch
    // reorders R's children to [c,a,b] (→ [R,c,a,b]). The patch replaces the full orderedIds array on the wire.
    private static void OrderPatchFixturesMatch()
    {
        var full = new RuntimeSceneDelta(true, "run", "screen:run:live",
            [Node("R"), Child("a", "R"), Child("b", "R"), Child("c", "R")], [], ["R", "a", "b", "c"]);
        AssertOrWriteFixture("order-patch-full.json", Serialize(full));

        var patch = new SceneOrderPatch(Roots: null, Parents: [new SceneOrderParentPatch("R", ["c", "a", "b"])]);
        var patchDelta = new RuntimeSceneDelta(false, "run", "screen:run:live", [], [], null);
        AssertOrWriteFixture("order-patch-delta.json",
            Encoding.UTF8.GetString(BrowserSceneDeltaMessage.Serialize(patchDelta, patch)));
    }

    private static RuntimeSceneDelta FullDelta(RuntimeSceneNodeDelta node) =>
        new(true, "run", "screen:run:live", [node], [], [node.Id]);

    private static RuntimeSceneNodeDelta Child(string id, string parentId) => new(
        Id: id, ParentId: parentId, Name: id, NodeType: "Control", Rect: null,
        Visible: true, Opacity: 1, ZIndex: null, Rotation: 0, Texture: null, NinePatch: false, Text: null);

    // A minimal-but-complete particle spec: meaningful Kind/Amount/Lifetime/OneShot/BaseColor, everything else at
    // Godot defaults. BaseColor carries #ff8040ff so the html-only wire color exercises the client channel-derive.
    private static RuntimeSceneParticleSpecSnapshot ParticleSpec() => new(
        Kind: "GPUParticles2D",
        Amount: 24,
        AmountRatio: 1,
        Lifetime: 1.5,
        LifetimeRandomness: 0,
        OneShot: true,
        Explosiveness: 0,
        Randomness: 0,
        Preprocess: 0,
        SpeedScale: 1,
        FixedFps: 0,
        LocalCoords: false,
        DrawOrder: 0,
        Seed: 0,
        EmissionShape: 0,
        EmissionOffset: new(0, 0),
        EmissionScale: new(1, 1),
        EmissionSphereRadius: 0,
        EmissionRingRadius: 0,
        EmissionRingInnerRadius: 0,
        EmissionRingHeight: 0,
        EmissionBoxExtents: new(0, 0),
        Direction: new(0, -1),
        Spread: 45,
        InitialVelocityMin: 0,
        InitialVelocityMax: 0,
        AngleMin: 0,
        AngleMax: 0,
        AngularVelocityMin: 0,
        AngularVelocityMax: 0,
        Gravity: new(0, 0),
        LinearAccelMin: 0,
        LinearAccelMax: 0,
        RadialAccelMin: 0,
        RadialAccelMax: 0,
        TangentialAccelMin: 0,
        TangentialAccelMax: 0,
        DampingMin: 0,
        DampingMax: 0,
        DampingAsFriction: false,
        OrbitVelocityMin: 0,
        OrbitVelocityMax: 0,
        ScaleMin: 1,
        ScaleMax: 1,
        HueVariationMin: 0,
        HueVariationMax: 0,
        AlignY: false,
        BaseColor: new RuntimeSceneColorSnapshot(1, 0.5, 0.25, 1, "#ff8040ff"),
        OriginX: 0,
        OriginY: 0,
        Texture: null,
        TextureWidth: 0,
        TextureHeight: 0,
        Hframes: 1,
        Vframes: 1,
        AnimLoop: false,
        AnimSpeedMin: 0,
        AnimSpeedMax: 0,
        AnimOffsetMin: 0,
        AnimOffsetMax: 0,
        BlendMode: 1,
        ColorRamp: null,
        ColorInitialRamp: null,
        ScaleCurve: null,
        ScaleCurveX: null,
        ScaleCurveY: null,
        AlphaCurve: null,
        HueCurve: null);

    private static string WireFixturePath(string file)
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "CouchCoop.sln")))
        {
            dir = dir.Parent;
        }

        if (dir is null)
        {
            throw new Exception("BrowserSceneDeltaMessageTests: could not locate repo root (CouchCoop.sln) for wire fixtures.");
        }

        return Path.Combine(dir.FullName, "tests", "fixtures", "wire", file);
    }

    private static RuntimeSceneNodeDelta Node(string id) => new(
        Id: id, ParentId: null, Name: id, NodeType: "Control", Rect: null,
        Visible: true, Opacity: 1, ZIndex: null, Rotation: 0, Texture: null, NinePatch: false, Text: null);

    private static RuntimeSceneDelta Delta(params RuntimeSceneNodeDelta[] upserts) =>
        new(false, "run", "screen:run:live", upserts, [], null);

    private static string Serialize(RuntimeSceneDelta delta) =>
        Encoding.UTF8.GetString(BrowserSceneDeltaMessage.Serialize(delta));

    private static RuntimeSceneVector2Snapshot V(double x, double y) => new(x, y);

    private static void ColorSerializesHtmlOnly()
    {
        var node = Node("a") with { Modulate = new RuntimeSceneColorSnapshot(0.1, 0.2, 0.3, 1, "#1a334cff") };
        var json = Serialize(Delta(node));
        Assert(json.Contains("\"modulate\":{\"html\":\"#1a334cff\"}", StringComparison.Ordinal), "modulate ships html-only");
        Assert(!json.Contains("\"r\":0.1", StringComparison.Ordinal), "color channels dropped from the wire");
    }

    private static void Vector2SerializesFloatShortestRoundTrip()
    {
        // 0.1f promoted to double is 0.10000000149011612; the float cast must recover the shortest "0.1".
        var node = Node("a") with { Transform = new RuntimeSceneTransform2DSnapshot(V(1, 0), V(0, 1), V((double)0.1f, 128.5)) };
        var json = Serialize(Delta(node));
        Assert(json.Contains("\"origin\":{\"x\":0.1,\"y\":128.5}", StringComparison.Ordinal),
            $"vector2 float shortest round-trip; got: {json}");
        Assert(!json.Contains("0.10000000149011612", StringComparison.Ordinal), "no full-double promotion on the wire");
    }

    private static void ResourceRefSerializesPathOnly()
    {
        var node = Node("a") with { Texture = new RuntimeSceneResourceRefSnapshot("Texture", "res://images/x.png", "Texture2D", "x") };
        var json = Serialize(Delta(node));
        Assert(json.Contains("\"texture\":{\"resourcePath\":\"res://images/x.png\"}", StringComparison.Ordinal), "texture ships path-only");
        Assert(!json.Contains("Texture2D", StringComparison.Ordinal) && !json.Contains("\"resourceType\"", StringComparison.Ordinal),
            "resource-ref metadata (field/type/name) dropped");
    }

    private static void NestedColorsInTextAreSlimmed()
    {
        // A Text snapshot with nested TextColor / OutlineColor — the converter must reach INTO the nested graph.
        var text = new RuntimeSceneTextPropertiesSnapshot(
            Text: "HP", RawText: null, RichTextEnabled: null, Source: "label", DiagnosticSurface: "surf",
            Font: null, FontSize: 24, LineHeight: null,
            TextColor: new RuntimeSceneColorSnapshot(1, 1, 1, 1, "#ffffffff"),
            OutlineColor: new RuntimeSceneColorSnapshot(0, 0, 0, 1, "#000000ff"),
            OutlineSize: 2, Shadow: null, RichTextSpans: [], Notices: []);
        var json = Serialize(Delta(Node("a") with { Text = text }));
        Assert(json.Contains("\"textColor\":{\"html\":\"#ffffffff\"}", StringComparison.Ordinal), "nested textColor slimmed to html");
        Assert(json.Contains("\"outlineColor\":{\"html\":\"#000000ff\"}", StringComparison.Ordinal), "nested outlineColor slimmed to html");
    }

    private static void DiscriminatorSuffixAndShapeIntact()
    {
        var json = Serialize(Delta(Node("a")));
        Assert(json.EndsWith(",\"type\":\"scene-delta\"}", StringComparison.Ordinal), "type discriminator spliced last");
        Assert(json.StartsWith("{\"full\":false", StringComparison.Ordinal), "envelope camelCase shape intact");
        Assert(json.Contains("\"upserts\":[{", StringComparison.Ordinal), "upserts present");
    }

    private static void FloatCastLosslessForProducerTransforms()
    {
        // The producer streams Godot float32 transforms promoted to double. Casting back to float and formatting
        // must recover a string that parses to the SAME float32 — no drift at the client's consumption precision.
        double[] samples = [(double)0.1f, (double)1.3125f, (double)959.5f, (double)-0.0009765625f, (double)1920f];
        foreach (var sample in samples)
        {
            var node = Node("a") with { Transform = new RuntimeSceneTransform2DSnapshot(V(1, 0), V(0, 1), V(sample, 0)) };
            var json = Serialize(Delta(node));
            // Extract the x we wrote and re-parse it as float; it must equal the source float32.
            var marker = "\"origin\":{\"x\":";
            var start = json.IndexOf(marker, StringComparison.Ordinal) + marker.Length;
            var end = json.IndexOf(',', start);
            var written = float.Parse(json[start..end], System.Globalization.CultureInfo.InvariantCulture);
            Assert(written == (float)sample, $"float round-trip lossless for {sample} (wrote {json[start..end]})");
        }
    }

    // GOLDEN: an exact expected JSON for a representative node — catches accidental field renames / reordering /
    // default-omission regressions. A node with a mix of default (omitted) and non-default (written) fields.
    private static void GoldenBytesForRepresentativeNode()
    {
        var node = new RuntimeSceneNodeDelta(
            Id: "42", ParentId: "7", Name: "Card", NodeType: "Control", Rect: null,
            Visible: false, Opacity: 0.5, ZIndex: 3, Rotation: 0, Texture: new RuntimeSceneResourceRefSnapshot("Texture", "res://images/card.png", "Texture2D", "card"),
            NinePatch: false, Text: null)
        {
            Modulate = new RuntimeSceneColorSnapshot(1, 1, 1, 1, "#ffffffff"),
            ScaleX = 1, ScaleY = 2, PivotX = 0, PivotY = 0,
            Transform = new RuntimeSceneTransform2DSnapshot(new(1, 0), new(0, 1), new((double)960.5f, (double)540f)),
            LocalRect = new RuntimeSceneRect2Snapshot(new(0, 0), new((double)100f, (double)16f)),
            ShowBehindParent = false, ClipChildren = 0, SpineLooping = true, ParticleRestartEpoch = 0,
        };
        var json = Serialize(Delta(node));
        const string expected =
            "{\"full\":false,\"screenType\":\"run\",\"screenInstanceId\":\"screen:run:live\"," +
            "\"upserts\":[{\"id\":\"42\",\"parentId\":\"7\",\"name\":\"Card\",\"nodeType\":\"Control\"," +
            "\"texture\":{\"resourcePath\":\"res://images/card.png\"}," +
            "\"modulate\":{\"html\":\"#ffffffff\"}," +
            "\"transform\":{\"xAxis\":{\"x\":1,\"y\":0},\"yAxis\":{\"x\":0,\"y\":1},\"origin\":{\"x\":960.5,\"y\":540}}," +
            "\"localRect\":{\"position\":{\"x\":0,\"y\":0},\"size\":{\"x\":100,\"y\":16}}," +
            "\"zIndex\":3,\"visible\":false,\"opacity\":0.5,\"scaleY\":2}]," +
            "\"removedIds\":[],\"type\":\"scene-delta\"}";
        Assert(json == expected, $"golden node bytes; got:\n{json}\nexpected:\n{expected}");
    }

    // Every value-type field at its client fallback default is OMITTED (nulled by the DTO → WhenWritingNull).
    private static void DefaultValuedFieldsAreOmitted()
    {
        // A node with EVERY omittable field at its default. Only id/name/nodeType survive.
        var node = Node("a"); // Visible true, Opacity 1, Scale 1, Pivot 0, NinePatch false, etc.
        var json = Serialize(Delta(node));
        foreach (var omitted in new[]
        {
            "\"visible\"", "\"opacity\"", "\"scaleX\"", "\"scaleY\"", "\"pivotX\"", "\"pivotY\"",
            "\"ninePatch\"", "\"showBehindParent\"", "\"clipChildren\"", "\"focused\"", "\"richText\"",
            "\"textureFlipH\"", "\"textureFlipV\"", "\"particleEmitting\"", "\"particleRestartEpoch\"",
            "\"spineTrackTime\"", "\"spineLooping\"", "\"rotation\"", "\"zIndex\"",
        })
        {
            Assert(!json.Contains(omitted, StringComparison.Ordinal), $"default-valued field {omitted} omitted");
        }
        Assert(json.Contains("\"id\":\"a\"", StringComparison.Ordinal), "id always written");
    }

    // Meaningful non-default value types are WRITTEN (a blanket WhenWritingDefault would WRONGLY drop these).
    private static void MeaningfulNonDefaultsAreWritten()
    {
        var node = Node("a") with { Visible = false, Opacity = 0, SpineLooping = false, NinePatch = true };
        var json = Serialize(Delta(node));
        Assert(json.Contains("\"visible\":false", StringComparison.Ordinal), "visible:false written (not the true default)");
        Assert(json.Contains("\"opacity\":0", StringComparison.Ordinal), "opacity:0 written (not the 1 default)");
        Assert(json.Contains("\"spineLooping\":false", StringComparison.Ordinal), "spineLooping:false written (not the true default)");
        Assert(json.Contains("\"ninePatch\":true", StringComparison.Ordinal), "ninePatch:true written");
        Assert(!json.Contains("\"rotation\"", StringComparison.Ordinal), "dead rotation field killed end-to-end");
    }

    // R13 CONTENT KEY: WireNodeDelta is an EXPLICIT field-by-field projection of the producer's node, so a new
    // producer field is SILENTLY DROPPED unless FromNode lists it (the PinnedLoopAnim lesson). Prove the pooled-card
    // content identity reaches the wire under its camelCase name — `contentKey` is the property the client keys its
    // pool-recycling DOM adoption on — and that a node without one (almost all of them) still omits the field.
    private static void ContentKeyReachesTheWire()
    {
        var json = Serialize(Delta(Node("card") with { ContentKey = "nc:Strike#12" }));
        Assert(json.Contains("\"contentKey\":\"nc:Strike#12\"", StringComparison.Ordinal),
            $"content key projected onto the wire; got: {json}");

        Assert(!Serialize(Delta(Node("a"))).Contains("\"contentKey\"", StringComparison.Ordinal),
            "content key omitted when the producer sent none");
    }

    // PER-ROLE RICH-TEXT FONTS: same lesson as ContentKey — WireNodeDelta is an EXPLICIT field-by-field projection,
    // so a producer field the client's reader is already waiting for is SILENTLY DROPPED unless FromNode lists it.
    // The three-way static-field lockstep can't catch that: it reflects over RuntimeSceneNodeDelta (the producer
    // record), never over the wire DTO. Prove all nine reach the wire under the camelCase names sceneTree.ts /
    // SceneDeltaReader read, in the shapes they read them in (a slimmed `{resourcePath}` for the fonts, bare numbers
    // for the scalars) — and that a node with none of them (essentially every node) still omits all nine, so the
    // wire off the rich-text scenes is byte-identical.
    private static void RichRoleFontsReachTheWire()
    {
        var node = Node("title") with
        {
            RichText = true,
            RichBoldFont = new RuntimeSceneResourceRefSnapshot("Theme", "res://fonts/kreon_bold.ttf", "FontFile", "bold"),
            RichItalicFont = new RuntimeSceneResourceRefSnapshot("Theme", "res://fonts/kreon_italic.ttf", "FontFile", "it"),
            RichBoldItalicFont = new RuntimeSceneResourceRefSnapshot("Theme", "res://fonts/kreon_bold_italic.ttf", "FontFile", "bi"),
            RichBoldFontSizePx = 21,
            RichItalicFontSizePx = 22,
            RichBoldItalicFontSizePx = 23,
            RichBoldFontSpacingPx = 1,
            RichItalicFontSpacingPx = 2,
            RichBoldItalicFontSpacingPx = 3,
        };
        var json = Serialize(Delta(node));

        Assert(json.Contains("\"richBoldFont\":{\"resourcePath\":\"res://fonts/kreon_bold.ttf\"}", StringComparison.Ordinal),
            $"richBoldFont projected onto the wire as a slimmed resource ref; got: {json}");
        Assert(json.Contains("\"richItalicFont\":{\"resourcePath\":\"res://fonts/kreon_italic.ttf\"}", StringComparison.Ordinal),
            "richItalicFont projected onto the wire");
        Assert(json.Contains("\"richBoldItalicFont\":{\"resourcePath\":\"res://fonts/kreon_bold_italic.ttf\"}", StringComparison.Ordinal),
            "richBoldItalicFont projected onto the wire");
        Assert(json.Contains("\"richBoldFontSizePx\":21", StringComparison.Ordinal), "richBoldFontSizePx on the wire");
        Assert(json.Contains("\"richItalicFontSizePx\":22", StringComparison.Ordinal), "richItalicFontSizePx on the wire");
        Assert(json.Contains("\"richBoldItalicFontSizePx\":23", StringComparison.Ordinal), "richBoldItalicFontSizePx on the wire");
        Assert(json.Contains("\"richBoldFontSpacingPx\":1", StringComparison.Ordinal), "richBoldFontSpacingPx on the wire");
        Assert(json.Contains("\"richItalicFontSpacingPx\":2", StringComparison.Ordinal), "richItalicFontSpacingPx on the wire");
        Assert(json.Contains("\"richBoldItalicFontSpacingPx\":3", StringComparison.Ordinal), "richBoldItalicFontSpacingPx on the wire");

        var plain = Serialize(Delta(Node("a")));
        Assert(!plain.Contains("\"richBold", StringComparison.Ordinal) && !plain.Contains("\"richItalic", StringComparison.Ordinal),
            "all nine role fields omitted for a node the producer streamed none for (wire unchanged off rich scenes)");
    }

    // R19 WP-4 CLIP CONTENTS: same lesson as ContentKey / the role fonts — WireNodeDelta is an EXPLICIT
    // field-by-field projection, so a producer field the client's reader already waits for is SILENTLY DROPPED
    // unless FromNode lists it. `clipContents` is the flag that makes a non-painting layout container bound its
    // children (the ancient-event ContentContainer); it is a DIFFERENT Godot property from `clipChildren`, so
    // neither field can stand in for the other. It rides the wire only when TRUE — a false is the client default,
    // and omitting it is what keeps the bytes for the ~99% of nodes that do not clip byte-identical.
    private static void ClipContentsReachesTheWire()
    {
        var json = Serialize(Delta(Node("panel") with { ClipContents = true }));
        Assert(json.Contains("\"clipContents\":true", StringComparison.Ordinal),
            $"clipContents projected onto the wire; got: {json}");
        Assert(!json.Contains("\"clipChildren\"", StringComparison.Ordinal),
            "clipContents does NOT imply clipChildren (two different Godot properties)");

        Assert(!Serialize(Delta(Node("a"))).Contains("\"clipContents\"", StringComparison.Ordinal),
            "clipContents omitted for a non-clipping node (wire unchanged off the clipping containers)");
    }

    private static void FocusedReachesTheWire()
    {
        var focused = Serialize(Delta(Node("reward") with { Focused = true }));
        Assert(focused.Contains("\"focused\":true", StringComparison.Ordinal),
            $"authoritative focused:true projected onto the browser wire; got: {focused}");

        var unfocused = Serialize(Delta(Node("reward") with { Focused = false }));
        Assert(!unfocused.Contains("\"focused\"", StringComparison.Ordinal),
            "authoritative focused:false omitted as the browser's false default");
        Assert(!Serialize(Delta(Node("plain"))).Contains("\"focused\"", StringComparison.Ordinal),
            "focus omitted when the producer cannot read it");
    }

    private static void Assert(bool condition, string label)
    {
        if (!condition)
        {
            throw new Exception($"BrowserSceneDeltaMessageTests failed: {label}.");
        }
    }
}
