import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { describe, expect, it } from "vitest";

import { applySceneDelta, createMirrorState, parseSceneDelta } from "@/mirror/sceneTree";

// TS leg of the EXTENDED cross-language wire-fixture corpus (spine / particle / intent-frames / tween-hints /
// order-patch). Each file is generated byte-exactly by the server serializer (BrowserSceneDeltaMessageTests) and
// asserted in parallel by the C# reader (CouchCoop.MirrorProtocol.Tests/NewFixtureReaderTests.cs). A wire-format
// change on any of the three sides breaks a test.

function read(file: string): unknown {
  return JSON.parse(readFileSync(resolve(process.cwd(), `../tests/fixtures/wire/${file}`), "utf8"));
}

function applied(file: string) {
  const delta = parseSceneDelta(read(file));
  expect(delta).not.toBeNull();
  const state = createMirrorState();
  applySceneDelta(state, delta!);
  return state;
}

describe("extended wire-fixture corpus", () => {
  it("spine node: static clip block + volatile anim/trackTime/looping", () => {
    const state = applied("spine-node.json");
    const spine = state.nodes.get("spine")!;
    expect(spine.nodeType).toBe("SpineSprite");
    expect(spine.spineSceneResPath).toBe("res://scenes/enemy.tscn");
    expect(spine.spineNodePath).toBe("Skeleton");
    expect(spine.spineAnimations).toEqual(["idle", "attack"]);
    expect(spine.spineCurrentAnim).toBe("attack");
    expect(spine.spineTrackTime).toBe(0.5);
    expect(spine.spineLooping).toBe(false);
  });

  // The bite attack overlay (res://scenes/vfx/vfx_bite.tscn). Its ONE-SHOT nature is carried entirely by
  // `spineLooping: false` in the message that STARTS the clip — the renderer clamps on the last frame, so the
  // wire never needs an "animation finished" follow-up (round-8 item 10).
  it("vfx_bite node: one-shot overlay ships spineLooping=false with its start message", () => {
    const state = applied("spine-vfx-bite-node.json");
    const bite = state.nodes.get("vfx-bite")!;
    expect(bite.nodeType).toBe("SpineSprite");
    expect(bite.spineSceneResPath).toBe("res://scenes/vfx/vfx_bite.tscn");
    expect(bite.spineNodePath).toBe("SpineSprite");
    expect(bite.spineAnimations).toEqual(["bite"]);
    expect(bite.spineCurrentAnim).toBe("bite");
    expect(bite.spineLooping).toBe(false);
  });

  it("particle node: particleSpec + volatile emitting/restartEpoch", () => {
    const state = applied("particle-node.json");
    const glow = state.nodes.get("glow")!;
    expect(glow.particleSpec).not.toBeNull();
    expect(glow.particleSpec!.kind).toBe("GPUParticles2D");
    expect(glow.particleSpec!.amount).toBe(24);
    expect(glow.particleSpec!.lifetime).toBe(1.5);
    expect(glow.particleSpec!.oneShot).toBe(true);
    // The spec's `emitting` is always the placeholder false (the per-tick particleEmitting overrides it).
    expect(glow.particleSpec!.emitting).toBe(false);
    // baseColor arrived html-only → channels derived (#ff8040ff → [1, 0x80/255, 0x40/255, 1]).
    expect(glow.particleSpec!.baseColor).toEqual([1, 0x80 / 255, 0x40 / 255, 1]);
    expect(glow.particleEmitting).toBe(true);
    expect(glow.particleRestartEpoch).toBe(2);
  });

  it("intent-frames node: frame set + frame-0 texture override", () => {
    const state = applied("intent-frames-node.json");
    const intent = state.nodes.get("intent")!;
    expect(intent.intentFrames).not.toBeNull();
    expect(intent.intentFrames!.animationName).toBe("attack");
    expect(intent.intentFrames!.fps).toBe(15);
    expect(intent.intentFrames!.frames).toHaveLength(2);
    expect(intent.intentFrames!.frames[0].url).toBe("/res/images/intent_atlas.png");
    // applyIntentFrame0: node texture forced to frame 0.
    expect(intent.textureUrl).toBe(intent.intentFrames!.frames[0].url);
    expect(intent.textureRegion).not.toBeNull();
  });

  // A map quill stroke. The whole appearance is linePoints + lineWidth + lineColor: the producer measures NO
  // localRect for a Line2D, so `linePoints != null` is the only signal that this node paints anything (both the
  // element gate and the drawBox anchor key on it). The points are NODE-LOCAL and must survive verbatim — no
  // re-pairing, no transform folded in.
  it("line2d node: flat node-local points + width + colour, and NO localRect", () => {
    const state = applied("line2d-node.json");
    const stroke = state.nodes.get("stroke")!;
    expect(stroke.nodeType).toBe("Godot.Line2D");
    expect(stroke.linePoints).toEqual([17, 98, 457, 249, 390.25, 554.5]);
    expect(stroke.lineWidth).toBe(4);
    expect(stroke.lineColor?.html).toBe("#ff0000ff");
    expect(stroke.localRect).toBeNull();
    // Pen vs eraser is derived from the shader path — there is no eraser flag on the wire.
    expect(stroke.shaderId).toBe("res://shaders/map_drawing/line_draw.gdshader");
  });

  it("shader-params node: base kinds + Godot-native-first extended kinds pass through", () => {
    const state = applied("shader-params-node.json");
    const node = state.nodes.get("shaded")!;
    expect(node.shaderParams).not.toBeNull();
    expect(node.shaderParams!).toHaveLength(7);
    const byName = new Map(node.shaderParams!.map((p) => [p.name, p]));

    expect(byName.get("width")!.kind).toBe("number");
    expect(byName.get("width")!.number).toBe(0.075);

    expect(byName.get("center")!.kind).toBe("vector2");
    expect(byName.get("center")!.vector2).toEqual({ x: 0.5, y: 0.25 });

    // Extended kinds: the web ignores them for rendering, but they must survive the reader as pass-through data.
    expect(byName.get("tint3")!.kind).toBe("vector3");
    expect(byName.get("tint3")!.vector3).toEqual({ x: 1, y: 0.5, z: 0.25 });

    expect(byName.get("tint4")!.kind).toBe("vector4");
    expect(byName.get("tint4")!.vector4).toEqual({ x: 0.25, y: 0.5, z: 0.75, w: 1 });

    expect(byName.get("bounds")!.kind).toBe("rect2");
    expect(byName.get("bounds")!.rect2).toEqual({ x: 0, y: 0, width: 128, height: 64 });

    expect(byName.get("xform")!.kind).toBe("transform2d");
    expect(byName.get("xform")!.transform2d).toEqual([1, 0, 0, 1, 640, 360]);

    expect(byName.get("palette")!.kind).toBe("vector3Array");
    expect(byName.get("palette")!.numberArray).toEqual([1, 0, 0, 0, 1, 0]);
  });

  it("tween-hints delta: transform+opacity group pair + timing-only looping hint", () => {
    const state = applied("tween-hints-delta.json");
    expect(state.pendingHints).toHaveLength(3);

    const [move, fade, loop] = state.pendingHints;
    expect(move.targetId).toBe("card");
    expect(move.property).toBe("position");
    expect(move.group).toBe("g1");
    expect(move.endTransform).toEqual([1, 0, 0, 1, 640, 360]);

    expect(fade.property).toBe("modulate:a");
    expect(fade.group).toBe("g1");
    expect(fade.endOpacity).toBe(0);

    expect(loop.property).toBe("scale");
    expect(loop.durationMs).toBe(800);
    // A looping tween resolves no endpoint.
    expect(loop.endTransform).toBeNull();
    expect(loop.endOpacity).toBeNull();
  });

  // WS-3: the declarative card flights, read from the bytes the server serializer actually produces. The C# leg
  // (NewFixtureReaderTests.CardFlights) asserts the SAME fixture field-for-field. This matters more than a tween
  // hint's parity: the producer STOPS streaming a flight's node, so a field the client silently misreads leaves a
  // shuffled card frozen on the discard pile rather than merely un-eased.
  it("card-flight delta: two declarative flights, on their own array, with the no-trail case", () => {
    const state = applied("card-flight-delta.json");
    expect(state.pendingCardFlights).toHaveLength(2);
    expect(state.pendingHints, "flights never leak into the tween-hint array").toHaveLength(0);

    const [withTrail, noTrail] = state.pendingCardFlights;
    expect(withTrail.targetId).toBe("41");
    expect(withTrail.trailId).toBe("42");
    expect(withTrail.start).toEqual([300, 880]);
    expect(withTrail.end).toEqual([1620, 880]);
    expect(withTrail.control).toEqual([960, 280]);
    expect(withTrail.basis).toEqual([1, 0, 0, 1]);
    expect(withTrail.speed0).toBeCloseTo(1.18, 6);
    expect(withTrail.accel).toBeCloseTo(2.3, 6);
    expect(withTrail.duration).toBeCloseTo(1.4, 6);
    expect(withTrail.scale0).toBe(1);
    expect(withTrail.windowMs).toBe(3600);

    // The producer OMITS `trailId` when the game made no trail, so this pins that an absent key reads as null
    // rather than as an id that would join to nothing.
    expect(noTrail.targetId).toBe("51");
    expect(noTrail.trailId).toBeNull();
    expect(noTrail.basis).toEqual([0.5, 0, 0, 0.5]);
    expect(noTrail.scale0).toBe(0.5);

    // Neither entry names a kind, and both still arrive as the shuffle sweep — the reader normalizes the absence so
    // nothing downstream ever branches on a null.
    expect(withTrail.kind).toBe("shuffle");
    expect(withTrail.rot0).toBe(0);
    expect(noTrail.kind).toBe("shuffle");
  });

  // R13: the same array carrying the second kind. The C# leg (NewFixtureReaderTests.CardFlightKinds) asserts the
  // same three entries. The third is the load-bearing one: a kind this build has never seen must come out as the
  // shuffle motion, because the producer has stopped streaming that node and a dropped flight leaves it frozen —
  // whereas the wrong flavour of motion is merely wrong.
  it("card-flight discard delta: an explicit discard, a legacy entry, and an unknown kind that fails open", () => {
    const state = applied("card-flight-discard-delta.json");
    expect(state.pendingCardFlights).toHaveLength(3);

    const [discard, legacy, unknown] = state.pendingCardFlights;
    expect(discard.targetId).toBe("61");
    expect(discard.kind).toBe("discard");
    expect(discard.rot0).toBeCloseTo(-0.35, 6);
    // The discard fly starts at the card's place in the HAND, not at a pile.
    expect(discard.start).toEqual([960, 1180]);
    expect(discard.windowMs).toBe(3200);

    // The producer omits BOTH keys for a shuffle, so this pins that the pre-R13 bytes still read as a shuffle.
    expect(legacy.targetId).toBe("71");
    expect(legacy.kind).toBe("shuffle");
    expect(legacy.rot0).toBe(0);

    expect(unknown.targetId).toBe("81");
    expect(unknown.kind).toBe("shuffle");
    expect(unknown.rot0).toBeCloseTo(0.75, 6);
  });

  it("order-patch: keyframe base order, then compact patch reorder", () => {
    const state = createMirrorState();
    applySceneDelta(state, parseSceneDelta(read("order-patch-full.json"))!);
    expect(state.orderedIds).toEqual(["R", "a", "b", "c"]);

    const patch = parseSceneDelta(read("order-patch-delta.json"));
    expect(patch).not.toBeNull();
    expect(patch!.orderPatch).not.toBeNull();
    applySceneDelta(state, patch!);
    expect(state.orderedIds).toEqual(["R", "c", "a", "b"]);
  });
});
